/*
 * One entry point for the hw-ab workflow.
 *
 * The underlying scripts take full paths, which are long enough to mistype and
 * are fully derivable from a case name and a side: every artifact of case C on
 * side S lives at tests/hw-ab/out/<C>/<S>.{hex,log}. This wrapper does that
 * derivation, resolves a case name from any unique substring of it, and hands
 * the result to build-ab.js / run-capture.js / diff-ab.js unchanged.
 *
 * It adds no behaviour of its own beyond the `ab` sequence: each command is a
 * single child process whose exit code is passed through verbatim, so the exit
 * codes documented for those scripts are the exit codes seen here.
 *
 * Paths are resolved from this file's location, never from the working
 * directory, so the command works from anywhere.
 */

"use strict";

const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");

const hwabDir = __dirname;
const pxtDir = path.resolve(hwabDir, "..", "..");
const outDir = path.join(hwabDir, "out");

// Same resolution as gen-project.js and build-ab.js: PXT_TARGET_DIR, else the
// sibling pxt-microbit checkout.
const targetSpec = process.env.PXT_TARGET_DIR || path.join(pxtDir, "..", "pxt-microbit");

const SIDES = ["candidate", "reference"];

// The soak program (generated by gen-project.js alongside the CASES table)
// prints HWAB SOAK heap telemetry forever and never a HWAB PASS verdict, so a
// plain capture of it
// can only time out, and a soak-mode capture of any other case can only
// report a stall. Both mismatches are refused up front.
const SOAK_CASE = "soak";

const USAGE = [
    "Usage: node tests/hw-ab/hwab.js <command> [args]",
    "       npm run hwab -- <command> [args]",
    "",
    "One entry point for the hw-ab hardware A/B workflow. Hex and log paths are",
    "derived from the case name and the side, so only the case is ever typed:",
    "case C on side S is tests/hw-ab/out/<C>/<S>.{hex,log}.",
    "",
    "Commands:",
    "  build [args...]              build the hexes; every argument is passed to",
    "                               build-ab.js unchanged (--help lists them)",
    "  capture <case> [side]        flash one hex and capture its serial output;",
    "        [--timeout <sec>]      side is candidate (default) or reference.",
    "        [--soak <minutes>]     --soak is for the soak case, which prints",
    "                               heap telemetry instead of a verdict",
    "  diff <case>                  diff the case's candidate and reference logs",
    "  ab <case> [--timeout <sec>]  the whole per-case loop on one board: capture",
    "                               candidate, capture reference, then diff",
    "  cases                        list the known cases and which hexes and logs",
    "                               exist right now",
    "  help                         this text",
    "",
    "A case may be named exactly or by any unique substring of its name, so",
    "\"truthiness\" and \"iface\" resolve; an ambiguous substring like \"condition\"",
    "is rejected with the candidate list rather than guessed.",
    "",
    "Examples:",
    "  npm run hwab -- build --v2-only --ref-switches \"<optOutSwitch,...>\"",
    "  npm run hwab -- ab truthiness",
    "  node tests/hw-ab/hwab.js ab truthiness",
    "",
    "Exit codes: the invoked script's own code, verbatim; `ab` reports the first",
    "failing stage's. 0 for help, 2 for an unknown command or bad arguments."
].join("\n");

function usage(stream) {
    stream.write(USAGE + "\n");
}

// Exit 2 is this wrapper's own "you asked for something I cannot turn into a
// command" code; it never overlaps with a child's, because no child runs.
function fail(msg) {
    process.stderr.write("hwab: " + msg + "\n");
    process.exit(2);
}

function say(msg) {
    process.stdout.write("hwab: " + msg + "\n");
}

// ---- case names -----------------------------------------------------------

function targetDir() {
    try {
        const resolved = fs.realpathSync(targetSpec);
        if (fs.statSync(resolved).isDirectory()) return resolved;
    } catch (e) { /* no target checkout */ }
    return "";
}

function isDir(p) {
    try { return fs.statSync(p).isDirectory(); } catch (e) { return false; }
}

// The generated cases.txt is authoritative -- it is what build-ab.js iterates.
// out/ is the fallback for a checkout with no target beside it, and is enough
// for anything that only reads already-built artifacts.
function knownCases() {
    const target = targetDir();
    if (target) {
        const casesFile = path.join(target, "projects", "hw-ab", "cases.txt");
        if (fs.existsSync(casesFile)) {
            const names = fs.readFileSync(casesFile, "utf8").split("\n")
                .map(l => l.replace(/\r$/, ""))
                .filter(l => l.length > 0);
            if (names.length) return { names: names, source: casesFile };
        }
    }
    if (isDir(outDir)) {
        const names = fs.readdirSync(outDir)
            .filter(e => isDir(path.join(outDir, e))).sort();
        if (names.length) return { names: names, source: outDir };
    }
    fail("no cases known yet -- neither " +
        path.join(targetSpec, "projects", "hw-ab", "cases.txt") + " nor " +
        outDir + " lists any.\n" +
        "  Run the build first: npm run hwab -- build --candidate-only --v2-only");
}

function resolveCase(name) {
    const known = knownCases();
    if (known.names.indexOf(name) >= 0) return name;
    const hits = known.names.filter(n => n.indexOf(name) >= 0);
    if (hits.length === 1) return hits[0];
    if (hits.length > 1)
        fail("'" + name + "' matches more than one case: " + hits.join(" ") + "\n" +
            "  Name one of them exactly, or use a substring that only one contains.");
    fail("no case matches '" + name + "'. Known cases (from " + known.source + "):\n" +
        "  " + known.names.join(" "));
}

function resolveSide(name) {
    if (SIDES.indexOf(name) >= 0) return name;
    fail("'" + name + "' is not a side -- expected " + SIDES.join(" or "));
}

function hexPath(caseName, side) {
    return path.join(outDir, caseName, side + ".hex");
}

function logPath(caseName, side) {
    return path.join(outDir, caseName, side + ".log");
}

function buildHint(side) {
    return side === "reference"
        ? "npm run hwab -- build --v2-only --ref-switches \"<optOutSwitch,...>\""
        : "npm run hwab -- build --candidate-only --v2-only";
}

function requireHex(caseName, side) {
    const hex = hexPath(caseName, side);
    let ok = false;
    try { ok = fs.statSync(hex).isFile(); } catch (e) { ok = false; }
    if (!ok)
        fail("no " + side + " hex for " + caseName + " at " + hex + "\n" +
            "  Build it first: " + buildHint(side));
    return hex;
}

// ---- child processes ------------------------------------------------------

// Never shell:true: the child is always node running a script whose path this
// process computed, and a path with a space in it must not be re-parsed by a
// shell. spawnSync with an argument array is also the form that behaves the
// same on Windows as it does elsewhere.
function run(script, args) {
    const res = spawnSync(process.execPath,
        [path.join(hwabDir, script)].concat(args), { stdio: "inherit" });
    if (res.error) {
        process.stderr.write("hwab: could not run " + script + ": " +
            res.error.message + "\n");
        return 1;
    }
    return res.status === null ? 1 : res.status;
}

// ---- commands -------------------------------------------------------------

function cmdBuild(argv) {
    return run("build-ab.js", argv);
}

function cmdCapture(argv) {
    let caseArg = null;
    let side = null;
    const passthrough = [];

    let soakMinutes = null;

    for (let i = 0; i < argv.length; i++) {
        const arg = argv[i];
        if (arg === "--timeout") {
            if (i + 1 >= argv.length) fail(arg + " needs a value");
            passthrough.push(arg, argv[++i]);
        } else if (arg === "--soak") {
            if (i + 1 >= argv.length) fail(arg + " needs a value");
            soakMinutes = argv[++i];
            if (!/^[1-9][0-9]*$/.test(soakMinutes))
                fail("--soak needs a positive whole number of minutes");
            passthrough.push(arg, soakMinutes);
        } else if (arg.charAt(0) === "-") {
            fail("unknown option: " + arg);
        } else if (caseArg === null) {
            caseArg = arg;
        } else if (side === null) {
            side = arg;
        } else {
            fail("unexpected argument: " + arg);
        }
    }

    if (caseArg === null) fail("capture needs a case name (see: hwab.js cases)");
    const caseName = resolveCase(caseArg);
    side = side === null ? "candidate" : resolveSide(side);

    if (caseName === SOAK_CASE && soakMinutes === null)
        fail("the soak program prints no verdict, so a plain capture of it can " +
            "only time out.\n  Give a duration: npm run hwab -- capture soak " +
            side + " --soak <minutes>");
    if (caseName !== SOAK_CASE && soakMinutes !== null)
        fail("--soak is for the soak case; " + caseName + " prints HWAB PASS, " +
            "not HWAB SOAK -- use a plain capture");

    const hex = requireHex(caseName, side);
    const log = logPath(caseName, side);
    say("capture " + caseName + " " + side);
    return run("run-capture.js", [hex, log].concat(passthrough));
}

function cmdDiff(argv) {
    if (argv.length < 1) fail("diff needs a case name (see: hwab.js cases)");
    if (argv.length > 1) fail("unexpected argument: " + argv[1]);
    const caseName = resolveCase(argv[0]);

    const missing = SIDES.filter(s => !fs.existsSync(logPath(caseName, s)));
    if (missing.length)
        fail("no " + missing.join(" and ") + " capture for " + caseName + ":\n" +
            missing.map(s => "  " + logPath(caseName, s)).join("\n") + "\n" +
            "  Capture it first: " +
            missing.map(s => "npm run hwab -- capture " + caseName + " " + s).join(" ; "));

    return run("diff-ab.js", [logPath(caseName, "candidate"),
                              logPath(caseName, "reference")]);
}

function cmdAb(argv) {
    let caseArg = null;
    const passthrough = [];

    for (let i = 0; i < argv.length; i++) {
        const arg = argv[i];
        if (arg === "--timeout") {
            if (i + 1 >= argv.length) fail("--timeout needs a value");
            passthrough.push(arg, argv[++i]);
        } else if (arg.charAt(0) === "-") {
            fail("unknown option: " + arg);
        } else if (caseArg === null) {
            caseArg = arg;
        } else {
            fail("unexpected argument: " + arg);
        }
    }

    if (caseArg === null) fail("ab needs a case name (see: hwab.js cases)");
    const caseName = resolveCase(caseArg);
    if (caseName === SOAK_CASE)
        fail("the soak program prints no pass/fail verdict, so there is " +
            "nothing for ab to sequence.\n" +
            "  Run each side for a duration, then compare:\n" +
            "    npm run hwab -- capture soak candidate --soak <minutes>\n" +
            "    npm run hwab -- capture soak reference --soak <minutes>\n" +
            "    npm run hwab -- diff soak");
    // Both hexes are checked up front: the run flashes the board twice, and
    // discovering the second hex is missing after the first flash wastes the
    // whole capture.
    for (const side of SIDES) requireHex(caseName, side);

    // One board, so the sides run in turn; run-capture.js does the flash and
    // waits for the board to come back each time.
    const stages = SIDES.map(side => ({
        name: "capture " + side,
        run: () => run("run-capture.js",
            [hexPath(caseName, side), logPath(caseName, side)].concat(passthrough))
    }));
    stages.push({
        name: "diff",
        run: () => run("diff-ab.js",
            [logPath(caseName, "candidate"), logPath(caseName, "reference")])
    });

    for (const stage of stages) {
        say("ab " + caseName + ": " + stage.name);
        const code = stage.run();
        if (code !== 0) {
            process.stderr.write("hwab: ab " + caseName + " FAILED at stage '" +
                stage.name + "' (exit " + code + ")\n");
            return code;
        }
    }
    say("ab " + caseName + ": OK -- both sides passed and the captures agree");
    return 0;
}

function pad(s, width) {
    return s.length >= width ? s : s + " ".repeat(width - s.length);
}

function cmdCases() {
    const known = knownCases();
    const headers = ["case", "cand.hex", "cand.log", "ref.hex", "ref.log"];
    const rows = known.names.map(name => [
        name,
        fs.existsSync(hexPath(name, "candidate")) ? "yes" : "-",
        fs.existsSync(logPath(name, "candidate")) ? "yes" : "-",
        fs.existsSync(hexPath(name, "reference")) ? "yes" : "-",
        fs.existsSync(logPath(name, "reference")) ? "yes" : "-"
    ]);

    const widths = headers.map((h, i) =>
        rows.reduce((w, r) => Math.max(w, r[i].length), h.length));
    const line = cells =>
        cells.map((c, i) => pad(c, widths[i])).join("  ").replace(/ +$/, "");

    process.stdout.write("hwab: cases from " + known.source + "\n");
    process.stdout.write("hwab: artifacts in " + outDir + "\n");
    process.stdout.write("\n");
    process.stdout.write(line(headers) + "\n");
    process.stdout.write(widths.map(w => "-".repeat(w)).join("  ") + "\n");
    for (const row of rows) process.stdout.write(line(row) + "\n");
    return 0;
}

// ---- dispatch -------------------------------------------------------------

function main(argv) {
    const cmd = argv[0];
    const rest = argv.slice(1);

    if (!cmd || cmd === "help" || cmd === "-h" || cmd === "--help") {
        usage(process.stdout);
        return 0;
    }

    switch (cmd) {
        case "build": return cmdBuild(rest);
        case "capture": return cmdCapture(rest);
        case "diff": return cmdDiff(rest);
        case "ab": return cmdAb(rest);
        case "cases": return cmdCases();
    }

    usage(process.stderr);
    process.stderr.write("\nhwab: unknown command: " + cmd + "\n");
    return 2;
}

process.exitCode = main(process.argv.slice(2));
