import * as Blockly from "blockly";

export enum MsgKey {
    REPORTERS_HUE = "REPORTERS_HUE",
    FUNCTIONS_CALL_TITLE = "FUNCTIONS_CALL_TITLE",
    FUNCTIONS_DEFNORETURN_TITLE = "FUNCTIONS_DEFNORETURN_TITLE",
    FUNCTIONS_GO_TO_DEFINITION_OPTION = "FUNCTIONS_GO_TO_DEFINITION_OPTION",
    FUNCTION_CALL_TOOLTIP = "FUNCTION_CALL_TOOLTIP",
    PROCEDURES_HUE = "PROCEDURES_HUE",
    PROCEDURES_CALLNORETURN_HELPURL = "PROCEDURES_CALLNORETURN_HELPURL",
    FUNCTIONS_DEFAULT_BOOLEAN_ARG_NAME = "FUNCTIONS_DEFAULT_BOOLEAN_ARG_NAME",
    FUNCTIONS_DEFAULT_STRING_ARG_NAME = "FUNCTIONS_DEFAULT_STRING_ARG_NAME",
    FUNCTIONS_DEFAULT_NUMBER_ARG_NAME = "FUNCTIONS_DEFAULT_NUMBER_ARG_NAME",
    FUNCTIONS_DEFAULT_ARRAY_ARG_NAME = "FUNCTIONS_DEFAULT_ARRAY_ARG_NAME",
    PROCEDURES_DEFNORETURN_TOOLTIP = "PROCEDURES_DEFNORETURN_TOOLTIP",
    PROCEDURES_DEFNORETURN_HELPURL = "PROCEDURES_DEFNORETURN_HELPURL",
    FUNCTIONS_DEFAULT_CUSTOM_ARG_NAME = "FUNCTIONS_DEFAULT_CUSTOM_ARG_NAME",
    FUNCTIONS_DEFAULT_FUNCTION_NAME = "FUNCTIONS_DEFAULT_FUNCTION_NAME",
    FUNCTION_CREATE_NEW = "FUNCTION_CREATE_NEW",
    FUNCTION_FLYOUT_LABEL = "FUNCTION_FLYOUT_LABEL",
    FUNCTIONS_EDIT_OPTION = "FUNCTIONS_EDIT_OPTION",
    FUNCTIONS_CREATE_CALL_OPTION = "FUNCTIONS_CREATE_CALL_OPTION",
    FUNCTIONS_DELETE_PARAMETER_BUTTON = "FUNCTIONS_DELETE_PARAMETER_BUTTON"
}

function defineMsg(key: MsgKey, value: string) {
    if (!Blockly.Msg[key]) {
        Blockly.Msg[key] = value;
    }
}

defineMsg(MsgKey.REPORTERS_HUE, "#A80000");

defineMsg(MsgKey.FUNCTIONS_CALL_TITLE, "call");

defineMsg(MsgKey.FUNCTIONS_DEFNORETURN_TITLE, "function");

defineMsg(MsgKey.FUNCTIONS_GO_TO_DEFINITION_OPTION, "Go to Definition");

defineMsg(MsgKey.FUNCTIONS_DEFAULT_BOOLEAN_ARG_NAME, "bool");

defineMsg(MsgKey.FUNCTIONS_DEFAULT_STRING_ARG_NAME, "text");

defineMsg(MsgKey.FUNCTIONS_DEFAULT_NUMBER_ARG_NAME, "num");

defineMsg(MsgKey.FUNCTIONS_DEFAULT_ARRAY_ARG_NAME, "array");

defineMsg(MsgKey.FUNCTIONS_DEFAULT_CUSTOM_ARG_NAME, "value");

defineMsg(MsgKey.FUNCTIONS_DEFAULT_FUNCTION_NAME, "doSomething");

defineMsg(MsgKey.FUNCTION_CREATE_NEW, "Make a Function");

defineMsg(MsgKey.FUNCTION_FLYOUT_LABEL, "Your Functions");

defineMsg(MsgKey.FUNCTIONS_EDIT_OPTION, "Edit Function");

defineMsg(MsgKey.FUNCTIONS_CREATE_CALL_OPTION, "Create 'call %1'");

defineMsg(MsgKey.FUNCTIONS_DELETE_PARAMETER_BUTTON, "Delete");