export const SET_INITIAL_STATE = "SET_INITIAL_STATE";
export const SET_INITIAL_FRAMES = "SET_INITIAL_FRAMES";
export const SET_INITIAL_TILEMAP = "SET_INITIAL_TILEMAP";

export const CHANGE_IMAGE_TOOL = "CHANGE_IMAGE_TOOL";
export const CHANGE_CURSOR_SIZE = "CHANGE_CURSOR_SIZE";
export const CHANGE_SELECTED_COLOR = "CHANGE_SELECTED_COLOR";
export const CHANGE_IMAGE_DIMENSIONS = "CHANGE_IMAGE_DIMENSIONS";
export const CHANGE_KEY_MODIFIERS = "CHANGE_KEY_MODIFIERS";
export const CHANGE_CURSOR_LOCATION = "CHANGE_CURSOR_LOCATION";

export const IMAGE_EDIT = "IMAGE_EDIT";
export const UNDO_IMAGE_EDIT = "UNDO_IMAGE_EDIT";
export const REDO_IMAGE_EDIT = "REDO_IMAGE_EDIT";

export const TOGGLE_ASPECT_RATIO = "TOGGLE_ASPECT_RATIO";
export const SET_GALLERY_OPEN = "SET_GALLERY_OPEN";

export const NEW_FRAME = "NEW_FRAME";
export const DELETE_FRAME = "DELETE_FRAME";
export const DUPLICATE_FRAME = "DUPLICATE_FRAME";
export const MOVE_FRAME = "MOVE_FRAME";
export const CHANGE_CURRENT_FRAME = "CHANGE_CURRENT_FRAME";
export const CHANGE_INTERVAL = "CHANGE_INTERVAL";
export const CHANGE_PREVIEW_ANIMATING = "CHANGE_PREVIEW_ANIMATING";
export const TOGGLE_ONION_SKIN_ENABLED = "TOGGLE_ONION_SKIN_ENABLED";
export const CHANGE_OVERLAY_ENABLED = "CHANGE_OVERLAY_ENABLED";
export const CHANGE_CANVAS_ZOOM = "CHANGE_CANVAS_ZOOM";
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const SWAP_FOREGROUND_BACKGROUND = "SWAP_FOREGROUND_BACKGROUND";
export const CHANGE_BACKGROUND_COLOR = "CHANGE_BACKGROUND_COLOR";

export const CHANGE_TILE_PALETTE_PAGE = "CHANGE_TILE_PALETTE_PAGE";
export const CHANGE_TILE_PALETTE_CATEGORY = "CHANGE_TILE_PALETTE_CATEGORY";

export const CHANGE_DRAWING_MODE = "CHANGE_DRAWING_MODE";
export const CREATE_NEW_TILE = "CREATE_NEW_TILE";
export const OPEN_TILE_EDITOR = "OPEN_TILE_EDITOR";
export const CLOSE_TILE_EDITOR = "CLOSE_TILE_EDITOR";
export const DELETE_TILE = "DELETE_TILE";
export const DISABLE_RESIZE = "DISABLE_RESIZE";