export enum ErrorCode {
    runEval = "runEval",
    addingMissingCriteria = "addingMissingCriteria",
    getProjectTextAsync = "getProjectTextAsync",
    getProjectMetaAsync = "getProjectMetaAsync",
    downloadTargetConfigAsync = "downloadTargetConfigAsync",
    evalMissingCriteria = "evalMissingCriteria",
    evalMissingPlan = "evalMissingPlan",
    evalParameterUnset = "evalParameterUnset",
    evalMissingCatalogParameter = "evalMissingCatalogParameter",
    loadCollectionFileFailed = "loadCollectionFileFailed",
    unableToGetIndexedDbRecord = "unableToGetIndexedDbRecord",
    unableToSetIndexedDbRecord = "unableToSetIndexedDbRecord",
    unableToDeleteIndexedDbRecord = "unableToDeleteIndexedDbRecord",
    unableToLoadCriteriaInstance = "unableToLoadCriteriaInstance",
    unableToExportRubric = "unableToExportRubric",
    unableToReadRubricFile = "unableToReadRubricFile",
    localStorageReadError = "localStorageReadError",
    localStorageWriteError = "localStorageWriteError",
    missingCriteriaInstance = "missingCriteriaInstance",
    validatorPlansNotFound = "validatorPlansNotFound",
    fetchRequestFailed = "fetchRequestFailed",
    fetchJsonDocAsync = "fetchJsonDocAsync",
    missingParameter = "missingParameter",
    selectedBlockWithoutOptions = "selectedBlockWithoutOptions",
}
