export const ADD_SKILL_MAP = "ADD_SKILL_MAP";
export const CLEAR_SKILL_MAPS = "CLEAR_SKILL_MAPS";
export const CLEAR_METADATA = "CLEAR_METADATA";
export const CHANGE_SELECTED_ITEM = "CHANGE_SELECTED_ITEM";
export const SET_SKILL_MAP_COMPLETED = "SET_SKILL_MAP_COMPLETED";

export const SET_HEADERID_FOR_ACTIVITY = "SET_HEADERID_FOR_ACTIVITY";
export const OPEN_ACTIVITY = "OPEN_ACTIVITY";
export const CLOSE_ACTIVITY = "CLOSE_ACTIVITY";
export const SAVE_AND_CLOSE_ACTIVITY = "SAVE_AND_CLOSE_ACTIVITY";
export const RESTART_ACTIVITY = "RESTART_ACTIVITY";

export const SET_USER = "SET_USER";
export const UPDATE_USER_COMPLETED_TAGS = "UPDATE_USER_COMPLETED_TAGS";
export const RESET_USER = "RESET_USER";

export const SET_PAGE_TITLE = "SET_PAGE_TITLE";
export const SET_PAGE_DESCRIPTION = "SET_PAGE_DESCRIPTION";
export const SET_PAGE_INFO_URL = "SET_PAGE_INFO_URL";
export const SET_PAGE_BACKGROUND_IMAGE_URL = "SET_PAGE_BACKGROUND_IMAGE_URL";
export const SET_PAGE_BANNER_IMAGE_URL = "SET_PAGE_BANNER_IMAGE_URL";
export const SET_PAGE_THEME = "SET_PAGE_THEME";
export const SET_PAGE_SOURCE_URL = "SET_PAGE_SOURCE_URL";
export const SET_PAGE_ALTERNATE_URLS = "SET_PAGE_ALTERNATE_URLS";

export const ENQUEUE_MODALS = "ENQUEUE_MODALS";
export const SET_MODAL = "SET_MODAL";
export const NEXT_MODAL = "NEXT_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const SHOW_COMPLETION_MODAL = "SHOW_COMPLETION_MODAL";
export const GRANT_SKILLMAP_BADGE = "GRANT_SKILLMAP_BADGE";

export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const SET_USER_PREFERENCES = "SET_USER_PREFERENCES";
export const USER_LOG_OUT = "USER_LOG_OUT";
export const SHOW_USER_PROFILE = "SHOW_USER_PROFILE";
export const HIDE_USER_PROFILE = "HIDE_USER_PROFILE";

export const SET_SHARE_STATUS = "SET_SHARE_STATUS";
export const SET_CLOUD_STATUS = "SET_CLOUD_STATUS";
export const SET_READY_RESOURCES = "SET_READY_RESOURCES";

export const SHOW_SELECT_LANGUAGE = "SHOW_SELECT_LANGUAGE";
export const HIDE_SELECT_LANGUAGE = "HIDE_SELECT_LANGUAGE";
export const SHOW_SELECT_THEME = "SHOW_SELECT_THEME";
export const HIDE_SELECT_THEME = "HIDE_SELECT_THEME";
export const SET_THEME_ID = "SET_THEME_ID";
