export const ADD_SKILL_MAP = "ADD_SKILL_MAP";
export const CLEAR_SKILL_MAPS = "CLEAR_SKILL_MAPS";
export const CHANGE_SELECTED_ITEM = "CHANGE_SELECTED_ITEM";
export const SET_HEADERID_FOR_ACTIVITY = "SET_HEADERID_FOR_ACTIVITY";
export const OPEN_ACTIVITY = "OPEN_ACTIVITY";
export const CLOSE_ACTIVITY = "CLOSE_ACTIVITY";
export const SAVE_AND_CLOSE_ACTIVITY = "SAVE_AND_CLOSE_ACTIVITY";


export const SET_PAGE_TITLE = "SET_PAGE_TITLE";
export const SET_PAGE_DESCRIPTION = "SET_PAGE_DESCRIPTION";
export const SET_PAGE_INFO_URL = "SET_PAGE_INFO_URL";

export const SHOW_COMPLETION_MODAL = "SHOW_COMPLETION_MODAL";
export const HIDE_COMPLETION_MODAL = "HIDE_COMPLETION_MODAL";
