export const ADD_SKILL_MAP = "ADD_SKILL_MAP";
export const CLEAR_SKILL_MAPS = "CLEAR_SKILL_MAPS";
export const CLEAR_METADATA = "CLEAR_METADATA";
export const CHANGE_SELECTED_ITEM = "CHANGE_SELECTED_ITEM";
export const SET_SKILL_MAP_COMPLETED = "SET_SKILL_MAP_COMPLETED";

export const SET_HEADERID_FOR_ACTIVITY = "SET_HEADERID_FOR_ACTIVITY";
export const OPEN_ACTIVITY = "OPEN_ACTIVITY";
export const CLOSE_ACTIVITY = "CLOSE_ACTIVITY";
export const SAVE_AND_CLOSE_ACTIVITY = "SAVE_AND_CLOSE_ACTIVITY";
export const RESTART_ACTIVITY = "RESTART_ACTIVITY";
export const SET_RELOAD_HEADER_STATE = "SET_RELOAD_HEADER_STATE";

export const SET_USER = "SET_USER";
export const UPDATE_USER_COMPLETED_TAGS = "UPDATE_USER_COMPLETED_TAGS";
export const RESET_USER = "RESET_USER";

export const SET_PAGE_TITLE = "SET_PAGE_TITLE";
export const SET_PAGE_DESCRIPTION = "SET_PAGE_DESCRIPTION";
export const SET_PAGE_INFO_URL = "SET_PAGE_INFO_URL";
export const SET_PAGE_BACKGROUND_IMAGE_URL = "SET_PAGE_BACKGROUND_IMAGE_URL";
export const SET_PAGE_BANNER_IMAGE_URL = "SET_PAGE_BANNER_IMAGE_URL";
export const SET_PAGE_THEME = "SET_PAGE_THEME";
export const SET_PAGE_SOURCE_URL = "SET_PAGE_SOURCE_URL";
export const SET_PAGE_ALTERNATE_URLS = "SET_PAGE_ALTERNATE_URLS";

export const SHOW_COMPLETION_MODAL = "SHOW_COMPLETION_MODAL";
export const SHOW_RESTART_ACTIVITY_MODAL = "SHOW_RESTART_ACTIVITY_MODAL";
export const SHOW_REPORT_ABUSE_MODAL = "SHOW_REPORT_ABUSE_MODAL";
export const SHOW_RESET_USER_MODAL = "SHOW_RESET_USER_MODAL";
export const SHOW_CARRYOVER_MODAL = "SHOW_CARRYOVER_MODAL";
export const SHOW_SHARE_MODAL = "SHOW_SHARE_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
