let math_op_1 = Math.sqrt(1);
let math_op_2 = Math.sin(2);
let math_op_3 = Math.cos(3);
let math_op_4 = Math.tan(4);
let math_op_5 = Math.atan2(5, 6);
let math_op_6 = Math.round(7);
let math_op_7 = Math.ceil(8);
let math_op_8 = Math.floor(9);
let math_op_9 = Math.trunc(0);
