let math_op_1 = Math.sqrt(3);
let math_op_2 = Math.sin(0);
let math_op_3 = Math.cos(1);
let math_op_4 = Math.tan(2);
let math_op_5 = Math.atan2(6, 7);
let math_op_6 = Math.round(5);
let math_op_7 = Math.ceil(4);
let math_op_8 = Math.floor(5);
let math_op_9 = Math.trunc(5);
