export enum ErrorCode {
    runEval = "runEval",
    addingMissingCriteria = "addingMissingCriteria",
    getProjectTextAsync = "getProjectTextAsync",
    getProjectMetaAsync = "getProjectMetaAsync",
    downloadTargetConfigAsync = "downloadTargetConfigAsync",
    evalMissingCriteria = "evalMissingCriteria",
    evalMissingPlan = "evalMissingPlan",
    loadCollectionFileFailed = "loadCollectionFileFailed",
    unableToGetIndexedDbRecord = "unableToGetIndexedDbRecord",
    unableToSetIndexedDbRecord = "unableToSetIndexedDbRecord",
    unableToDeleteIndexedDbRecord = "unableToDeleteIndexedDbRecord",
    loadUnrecognizedCatalogId = "loadUnrecognizedCatalogId",
    loadUnrecognizedParameter = "loadUnrecognizedParameter",
}
