export const ADD_SKILLS_MAP = "ADD_SKILLS_MAP";
export const CLEAR_SKILLS_MAPS = "CLEAR_SKILLS_MAPS";
export const CHANGE_SELECTED_ITEM = "CHANGE_SELECTED_ITEM";
export const SET_HEADERID_FOR_ACTIVITY = "SET_HEADERID_FOR_ACTIVITY";
export const OPEN_ACTIVITY = "OPEN_ACTIVITY";
export const CLOSE_ACTIVITY = "CLOSE_ACTIVITY";

export const SET_PAGE_TITLE = "SET_PAGE_TITLE";
export const SET_PAGE_DESCRIPTION = "SET_PAGE_DESCRIPTION";
export const SET_PAGE_INFO_URL = "SET_PAGE_INFO_URL";
