export const ADD_SKILLS_MAP = "ADD_SKILLS_MAP";
export const CLEAR_SKILLS_MAPS = "CLEAR_SKILLS_MAPS";
export const CHANGE_SELECTED_ITEM = "CHANGE_SELECTED_ITEM";
export const SET_HEADERID_FOR_ACTIVITY = "SET_HEADERID_FOR_ACTIVITY";
