namespace ts.pxtc {
    export function getHelpForKeyword(word: string, isPython: boolean): string {
        // TODO: Fill these in for TypeScript
        const tsHelp: pxt.Map<string> = {
            "abstract": null,
            "any": null,
            "as": null,
            "break": null,
            "case": null,
            "catch": null,
            "class": null,
            "continue": null,
            "const": null,
            "constructor": null,
            "debugger": null,
            "declare": null,
            "delete": null,
            "do": null,
            "else": null,
            "enum": null,
            "export": null,
            "extends": null,
            "false": lf("Represents the negative outcome of a logical expression"),
            "finally": null,
            "for": null,
            "from": null,
            "function": null,
            "get": null,
            "if": null,
            "implements": null,
            "in": null,
            "instanceof": null,
            "interface": null,
            "is": null,
            "let": null,
            "namespace": null,
            "new": null,
            "null": null,
            "private": null,
            "protected": null,
            "public": null,
            "return": null,
            "set": null,
            "static": null,
            "super": null,
            "switch": null,
            "this": null,
            "throw": null,
            "true": lf("Represents the positive outcome of a logical expression"),
            "try": null,
            "type": null,
            "typeof": null,
            "undefined": null,
            "void": null,
            "while": null,
            "with": null,
            "of": null
        }


        if (isPython) {
            // We don't actually support all of these! I just copied over all
            // of the reserved words
            const pyHelp: pxt.Map<string> = {
                "True": tsHelp["true"],
                "False": tsHelp["false"],
                "None": null,
                "abs": null,
                "all": null,
                "any": null,
                "ascii": null,
                "bin": null,
                "bool": null,
                "bytearray": null,
                "bytes": null,
                "callable": null,
                "chr": null,
                "classmethod": null,
                "compile": null,
                "complex": null,
                "copyright": null,
                "credits": null,
                "delattr": null,
                "dict": null,
                "dir": null,
                "divmod": null,
                "enumerate": null,
                "eval": null,
                "exec": null,
                "exit": null,
                "filter": null,
                "float": null,
                "format": null,
                "frozenset": null,
                "getattr": null,
                "globals": null,
                "hasattr": null,
                "hash": null,
                "help": null,
                "hex": null,
                "id": null,
                "input": null,
                "int": null,
                "isinstance": null,
                "issubclass": null,
                "iter": null,
                "len": null,
                "license": null,
                "list": null,
                "locals": null,
                "map": null,
                "max": null,
                "memoryview": null,
                "min": null,
                "next": null,
                "object": null,
                "oct": null,
                "open": null,
                "ord": null,
                "pow": null,
                "print": null,
                "property": null,
                "quit": null,
                "range": null,
                "repr": null,
                "reversed": null,
                "round": null,
                "set": null,
                "setattr": null,
                "slice": null,
                "sorted": null,
                "staticmethod": null,
                "str": null,
                "sum": null,
                "super": null,
                "tuple": null,
                "type": null,
                "vars": null,
            };

            return pyHelp[word];
        }
        else {
            return tsHelp[word];
        }
    }
}