name: Check if the commit is part of a merged PR
on:
  workflow_call:
    outputs:
      is_merged_pr:
        description: "Whether the current push came from a merged PR"
        value: ${{ jobs.check.outputs.is_merged_pr }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      is_merged_pr: ${{ steps.set-output.outputs.is_merged_pr }}
    steps:
      - name: Check if this commit is from a merged PR
        id: check-pr
        uses: actions/github-script@main
        with:
          script: |
            const commitSha = context.sha;
            const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha
            });

            const mergedPr = prs.find(pr => pr.merged_at !== null);
            core.setOutput("is_merged_pr", mergedPr ? "true" : "false");

      - id: set-output
        run: echo "is_merged_pr=${{ steps.check-pr.outputs.is_merged_pr }}" >> $GITHUB_OUTPUT
