name: pxt-buildmain

on:
  push:
    branches:
      - 'master'
      - 'main'
  create:

permissions:
  contents: write

jobs:
  tag-bump-commit:
    uses: ./.github/workflows/tag-bump-commit.yml

  build:
    name: buildmain
    runs-on: ubuntu-latest
    needs: tag-bump-commit

    steps:
      - uses: actions/checkout@main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: '16.x'
      - name: npm install
        run: |
          sudo apt-get install xvfb
          sudo npm install -g pxt
          npm install
      - name: npm test
        run: |
          npm test
        env:
          CROWDIN_KEY: ${{ secrets.CROWDIN_KEY }}
          PXT_ACCESS_TOKEN: ${{ secrets.PXT_ACCESS_TOKEN }}
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          PXT_ENV: production
          CHROME_BIN: chromium-browser
          DISPLAY: :99.0
          CI: true
