export const CHANGE_SELECTED_ASSET = "CHANGE_SELECTED_ASSET";
export const CHANGE_GALLERY_VIEW = "CHANGE_GALLERY_VIEW";
export const UPDATE_USER_ASSETS = "UPDATE_USER_ASSETS";
export const UPDATE_GALLERY_ASSETS = "UPDATE_GALLERY_ASSETS";